-- Migration: 20260703000000_simulacoes_and_tracking.sql
-- Descrição: Tabelas de simulações odontológicas e métricas de tracking com RLS completa e isolamento por usuário

-- 1. Tabela public.simulacoes
CREATE TABLE IF NOT EXISTS public.simulacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
  procedimento TEXT,
  img_original_url TEXT,
  img_simulada_url TEXT,
  nome_paciente TEXT,
  cor_utilizada TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.simulacoes ENABLE ROW LEVEL SECURITY;

-- 2. Tabela public.simulacao_tracking
CREATE TABLE IF NOT EXISTS public.simulacao_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('acerto', 'erro', 'refeita', 'salva')),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.simulacao_tracking ENABLE ROW LEVEL SECURITY;

-- 3. Políticas RLS para public.simulacoes
DROP POLICY IF EXISTS "Users can read own simulacoes" ON public.simulacoes;
DROP POLICY IF EXISTS "Admins can read all simulacoes" ON public.simulacoes;
DROP POLICY IF EXISTS "Users can insert own simulacoes" ON public.simulacoes;
DROP POLICY IF EXISTS "Users can delete own simulacoes" ON public.simulacoes;

CREATE POLICY "Admins can read all simulacoes"
ON public.simulacoes FOR SELECT
TO authenticated
USING (
  usuario_id = auth.uid() OR public.is_admin(auth.uid())
);

CREATE POLICY "Users can insert own simulacoes"
ON public.simulacoes FOR INSERT
TO authenticated
WITH CHECK (
  usuario_id = auth.uid()
);

CREATE POLICY "Users can delete own simulacoes"
ON public.simulacoes FOR DELETE
TO authenticated
USING (
  usuario_id = auth.uid() OR public.is_admin(auth.uid())
);

-- 4. Políticas RLS para public.simulacao_tracking
DROP POLICY IF EXISTS "Users can read own simulation tracking" ON public.simulacao_tracking;
DROP POLICY IF EXISTS "Admins can read all simulation tracking" ON public.simulacao_tracking;
DROP POLICY IF EXISTS "Users can insert own simulation tracking" ON public.simulacao_tracking;

CREATE POLICY "Admins can read all simulation tracking"
ON public.simulacao_tracking FOR SELECT
TO authenticated
USING (
  user_id = auth.uid() OR public.is_admin(auth.uid())
);

CREATE POLICY "Users can insert own simulation tracking"
ON public.simulacao_tracking FOR INSERT
TO authenticated
WITH CHECK (
  user_id = auth.uid()
);
